### ISSUE TITLE
self.extra_repository_files is None

### ISSUE THREAD

**Issue by seem8** [fepitre/rpmreproduce#1]
Hi.
I saw Your post in a Fedora mailing lists and decided to look around. It's pretty neat, thanks.

I'm following readme and trying to verified build, but I'm stuck at self.extra_repository_files, which is none and that's nothing to put into repo_src in the for loop.

```
python3 rpmreproduce.py --output=./artifacts --builder=mock tests/data/qubes-core-agent-4.1.23-1.fc32.x86_64.buildinfo 
Traceback (most recent call last):
  File "/home/lukasz/progi/rpm/rpmreproduce/rpmreproduce.py", line 832, in <module>
    sys.exit(main())
  File "/home/lukasz/progi/rpm/rpmreproduce/rpmreproduce.py", line 824, in main
    rebuilder.run(builder=args.builder, output=realpath(args.output),
  File "/home/lukasz/progi/rpm/rpmreproduce/rpmreproduce.py", line 667, in run
    self.prepare_dnfcache()
  File "/home/lukasz/progi/rpm/rpmreproduce/rpmreproduce.py", line 363, in prepare_dnfcache
    for repo_src in self.extra_repository_files:
TypeError: 'NoneType' object is not iterable
```

**Comment by fepitre** [comment]
@seem8 Yes just a little fix to do if no extra repository is provided. Also, I should update my example because it will miss Qubes related packages in...extra repositories ;)

**Comment by fepitre** [comment]
@seem8 Do you mind to try on your side please? It should fail nicely now because it would not find Qubes dependencies. If you add extra repository as in the updated example, it should work. BTW, thank you to give it a try. It's a really WIP tool so there is still a lot of work to do :)
