### ISSUE TITLE
Failed to get RPM signature keyid: bad magic: b'itl'

### ISSUE THREAD

**Issue by gonzalo-bulnes** [fepitre/rpmreproduce#3]
Hi @fepitre !

I'm trying to figure out how far I am from being able to reproduce some of my personal packages ([context](https://github.com/gonzalo-bulnes/qubes-mgmt-salt-user/issues/22)). 

I've been generating a `.buildinfo` file using a variant of [Qubes OS' `rpmbuildinfo`](https://github.com/QubesOS/qubes-builder-rpm/blob/mm_ba366097/scripts/rpmbuildinfo) script, and feeding it to `rpmreproduce`.

I got this error recently. I wouldn't bug you with unspecific errors, but the "ITL" mention makes be believe it may actually be specific to your `rpmreproduce` tool and/or Qubes OS?

```sh
ERROR:rpmreproduce:Failed to get RPM signature keyid: Invalid rpm: bad magic: b'itl'
```

This happens, as far as I'm understanding, when attempting to verify a package that's been downloaded. More context:

```sh
DEBUG:rpmreproduce:Downloading https://kojipkgs.fedoraproject.org/packages/openh264/2.1.1/1.fc32/data/signed/12c944d0/x86_64/gstreamer1-plugin-openh264-1.16.2-2.fc32.x86_64.rpm to /tmp/rpmreproduce/cache/rpms/gstreamer1-plugin-openh264-1.16.2-2.fc32.x86_64.rpm.UNTRUSTED
Failed to get RPM signature keyid: Invalid rpm: bad magic: b'itl'
ERROR:rpmreproduce:Failed to get RPM signature keyid: Invalid rpm: bad magic: b'itl'
```

I've built the package in a Fedora 32 template, so maybe that `b'itl'` has to do with that, rather than with `rpmreproduce`.
Does that ring any bell?

Beyond that, would you say that using `rpmreproduce` seems like a sound approach to reproducing personal RPM packages?

**Comment by gonzalo-bulnes** [comment]
Hey @fepitre,

I'll close this for now. It struck me that **openh264** seems very unrelated to my build, so I'm in the process of trimming down the number of packages in my buildinfo file, and making progress.

Once I can get to a successful build, I'll do something like a bisect to figure out which packages are actually relevant to making my builds reproducible and make sure those are specified in my buildinfo files.

Apologies for the noise. 🫤

**Comment by fepitre** [comment]
No problem, I'm happy to see this early tool is used! There is several bugs for sure but any feedback is useful. It can be on Qubes OS forum.
